### ISSUE TITLE
Create endpoint for Github Webhooks

### ISSUE THREAD

**Issue by tallysmartins** [elixir-bench/elixir-bench-api#26]
Create the endpoint to listen to activities of registered repos and trigger Job runs according to new commits in branches and pull requests.

- [x] 1. Investigate how github send hook payloads and what events we want to listen

- [x] 2. Investigate how to guarantee security and certify hook requests came from the right source
   
- [x] 3. Initial implementation for a single event

- [x] 4. Implementation for all the other events

- [ ] 5. Implement auth verification (secret and hash stuff)

**Comment by tallysmartins** [comment]
@PragTob @michalmuskala I created this issue to point some considerations regarding this task

**Subtask 1:**  I found in the [webhook events docs](https://developer.github.com/v3/activity/events/types/) that two events seems to be the ones that we need the ```push``` and ```pull_requests``` We can start with any of them. Github requests come with a ```X-GitHub-Event``` that says the type of the event, aka **push, pull_request, comment** and the action associated, **opened, edited, closed**, etc. 

**Subtask 2:**  Its possible to set up a secret key that is used to hash the request body with HMAC-sha1 that is sent in the header as  ```X-Hub-Signature```.

**Subtask 3:**  I created a new controller and started implementation of ```pull_request``` using the [payload from the docs](https://developer.github.com/v3/activity/events/types/#pullrequestevent) and without much verification. But I would like to discuss some points before continue on this:

 - 1 If a Job exists for a given branch and commit, do not trigger another one, right?
 - 2 If a Job is triggered from a PR I see two options: The first is to find the PR reference in the base repository and trigger a Job associated with it. The second is just create a new repository object related to the source repo and trigger a job associated with it. The first one makes more sense for me but any of them can be the solution.
